name: Deploy

on:
  workflow_dispatch:

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP POST
        run: curl POST "https://api.vercel.com/v1/integrations/deploy/prj_Ic8EhIc5lfr50oq647xh7eH5hxvI/OK24kzIw1K"
